blank_issues_enabled: false
contact_links:
  - name: 🛟 Support 🛟
    url: https://omarchy.org/discord
    about: Need help? Join our Discord community for support with any issues. GitHub issues should be used for verified bugs, documentation, and enhancement proposals only.
